### ISSUE TITLE
Фестивали и регулярные мероприятия

### ISSUE THREAD

**Issue by mikhailkataev** [alexandra-trisch/muenchen-wiki#14]
Предлагаю создать список регулярных фестивалей. Например, Tollwood и Auer Dult. Не Октоберфестом единым славится Мюнхен :)

**Comment by alexandra-trisch** [comment]
имеет ли это смысл, если эту информацию можно найти и в гугле? ну то есть мы выкладываем проверенные типа кафешки хорошие и т.д. С фестивалями сложнее, они как бы есть и все. Но если хочешь создай файлик именно про фестивали :)
