### ISSUE TITLE
Discussion follow-up: процедура оформления страхового случая при ДТП

### ISSUE THREAD

**Issue by sparfenyuk** [alexandra-trisch/muenchen-wiki#25]
**Входные данные**: есть зарегистрированное ДТП, требуется получить выплаты по страховке виновного.
**Что нужно**: пошаговая инструкция (+глоссарий терминов по-немецки) по следам обсуждения топика https://t.me/munichmoney/134.

Assigned to: @Zifius

**Comment by alexandra-trisch** [comment]
@Zifius ишью тебя ждет :)

**Comment by Zifius** [comment]
Test
