### ISSUE TITLE
Использовать русский язык в названиях

### ISSUE THREAD

**Issue by TikhonovAlexander** [alexandra-trisch/muenchen-wiki#27]
Тем людям, которые не знают немецкого, будь это те которые только собираются переезжать или те которые уже живут в Мюнхене может быть непонятно, что означает **Ärzte**, **Miete** **Versicherung** и тд.
Может лучше использовать русский язык или русский и рядом в скобочках немецкий вариант?

**Comment by alexandra-trisch** [comment]
Привычка не использовать кирилицу в названиях файлов. Не знаю, может и имеет смысл.

**Comment by Romanow88** [comment]
Как вариант можно использовать английские имена файлов.

**Comment by alexandra-trisch** [comment]
если не воспринимать это как файлы, а как названия статей, то я в принципе не против русских названий

**Comment by alexandra-trisch** [comment]
fixed in #29
