### ISSUE TITLE
Где можно сделать термин на прописку? 

### ISSUE THREAD

**Issue by cajoy** [alexandra-trisch/muenchen-wiki#44]
не могу понять как сделать термин для регистрации прописки

нашел эту ссылку но что тут выбирать не понятно: https://www.muenchen.de/rathaus/terminvereinbarung_bb.html 

? Ест какой то FAQ  по Мюнхену?

**Comment by sparfenyuk** [comment]
заходи в чат https://t.me/muenchentraktor, там оперативно подскажут

**Comment by Zifius** [comment]
Meldeangelegenheiten ➤ 
* An- oder Ummeldung - Einzelperson (для одного человека)
* An- oder Ummeldung - Familie (для семьи)
