### ISSUE TITLE
POI

### ISSUE THREAD

**Issue by sparfenyuk** [alexandra-trisch/muenchen-wiki#5]
Есть отличное [начинание о забегаловках](https://github.com/alexandra-trisch/muenchen-wiki/blob/master/%D0%9C%D0%B5%D1%81%D1%82%D0%B0%20%D0%B4%D0%BB%D1%8F%20%D0%B5%D0%B4%D1%8B.md), но информация нерепрезентативна. Неудобно вбивать всякий раз адрес и смотреть, где это место находится.

Предлагаю продублировать их непосредственно на карте. Должно получится нечто такое https://www.google.com/maps/d/viewer?mid=1Wi6U_Zk4AaMxE_Lqb4QmwOexKwc. Единственная забота заключается в том, что принимая очередной мерж реквест, автору репозитория нужно обновлять информацию на карте.

Однако, польза на лицо - достояние сообщества, которым наверняка будет пользоваться тысячи туристов.

**Comment by alexandra-trisch** [comment]
хорошая идея :) я давно хотела создать карту по мюнхену свою личную. можно замержить с информацией от других людей :)

**Comment by alexandra-trisch** [comment]
done
