### ISSUE TITLE
Кофе в Мюнхене

### ISSUE THREAD

**Issue by andklm** [alexandra-trisch/muenchen-wiki#6]
Benko Cafe
Luisenstraße 41, 80333 München
089 12765804

https://goo.gl/maps/r1NHmoCd75E2

Man Versus Machine Coffee Roasters
Müllerstraße 23, 80469 München
089 80046681

https://goo.gl/maps/DzmvqNPMZqs

Mi Piace 
Неплохая сеть

**Comment by cajoy** [comment]
А есть какие то места где можно например бесплатно поиграть в бильярд или настольный футбол?

**Comment by alexandra-trisch** [comment]
@andklm бенко кафе добавила на карту
